name: dart_spacetraders
description: A client for the [SpaceTraders API](https://spacetraders.io/).
version: 1.0.0
repository: https://github.com/FBanitz/dart_spacetraders

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
